# -*- coding: utf-8 -*-
"""tile_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qJXj8k3ZI0Z7n7puetJ82qfSKSu9ogd
"""

from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
from scipy.odr import ODR, Model, Data, RealData
from pylab import *
from matplotlib import pyplot as plt
from scipy import optimize
import os
from scipy.signal import find_peaks
from scipy import constants

plt.figure(figsize=(12, 8), dpi=80)
for file in os.listdir("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/rough"):
  data = np.loadtxt(open("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/rough/"+file,'rt').readlines(), dtype=float, delimiter="\t", skiprows=1)
  volt = data[:,4]
  peak = data[:,5]#/sum(data[:,5])

  div = int(file[-7:-4])
  peak = peak*100/div

  plt.plot(volt,peak, label = label)

plt.xlim(None, 1)

plt.xlabel("Pulse height (V)")
plt.ylabel("Counts")
plt.legend()
plt.title("Tile Comparison (thicker rig)")
plt.grid()
plt.show()

plt.figure(figsize=(12, 8), dpi=80)
for file in os.listdir("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/fine"):
  data = np.loadtxt(open("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/fine/"+file,'rt').readlines(), dtype=float, delimiter="\t", skiprows=1)
  volt = data[:,4]
  peak = data[:,5]#/sum(data[:,5])
  label = "tile "+file[5]
  div = int(file[-7:-4])
  peak = peak*100/div

  plt.plot(volt,peak, label = label)

plt.xlim(None, 1)

plt.xlabel("Pulse height (V)")
plt.ylabel("Counts")
plt.legend()
plt.title("Tile Comparison (thinner rig)")
plt.grid()
plt.show()

for i in [1,2,4,5,6]:
  for file in os.listdir("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/rough"):
    if int(file[5]) == i:
      data = np.loadtxt(open("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/rough/"+file,'rt').readlines(), dtype=float, delimiter="\t", skiprows=1)
      volt = data[:,4]
      peak = data[:,5]#/sum(data[:,5])
      label = "thick rig"
      div = int(file[-7:-4])
      peak = peak*100/div
      plt.plot(volt,peak, label = label, color ='b')

  for file in os.listdir("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/fine"):
    if int(file[5]) == i:
      data = np.loadtxt(open("/content/drive/MyDrive/tesi magistrale/muSR tests/tile_testing/data/fine/"+file,'rt').readlines(), dtype=float, delimiter="\t", skiprows=1)
      volt = data[:,4]
      peak = data[:,5]/3 #to normalize time
      label = "thin rig"
      div = int(file[-7:-4])
      peak = peak*100/div
      plt.plot(volt,peak, label = label, color ='r')

  plt.xlim(None, 1.2)
  plt.xlabel("Pulse height (V)")
  plt.ylabel("Counts")
  plt.legend()
  plt.title("Tile %s rig comparison"%i)
  plt.grid()
  plt.show()